exclude:
- /MSVC/.*
- /autogen.sh
- /bin/.*
- /contrib/src/.*
- /src/account.cpp
- /src/account.h
- /src/account_factory.cpp
- /src/account_factory.h
- /src/account_schema.h
- /src/archiver.cpp
- /src/archiver.h
- /src/array_size.h
- /src/base64.cpp
- /src/base64.h
- /src/buildinfo.cpp
- /src/call.cpp
- /src/call.h
- /src/call_factory.cpp
- /src/call_factory.h
- /src/client/.*
- /src/compiler_intrinsics.h
- /src/conference.cpp
- /src/conference.h
- /src/config/.*
- /src/dlfcn.c
- /src/dlfcn.h
- /src/dring/.*
- /src/enumclass_utils.h
- /src/fileutils.cpp
- /src/fileutils.h
- /src/hooks/.*
- /src/ice_socket.h
- /src/ice_transport.cpp
- /src/ice_transport.h
- /src/im/.*
- /src/ip_utils.cpp
- /src/ip_utils.h
- /src/logger.cpp
- /src/logger.h
- /src/manager.cpp
- /src/manager.h
- /src/map_utils.h
- /src/media/.*
- /src/noncopyable.h
- /src/plugin_loader.h
- /src/plugin_loader_dl.cpp
- /src/plugin_manager.cpp
- /src/plugin_manager.h
- /src/preferences.cpp
- /src/preferences.h
- /src/rational.h
- /src/registration_states.h
- /src/ring_api.cpp
- /src/ring_plugin.h
- /src/ring_types.h
- /src/ringdht/eth/.*
- /src/ringdht/namedirectory.cpp
- /src/ringdht/namedirectory.h
- /src/ringdht/sip_transport_ice.cpp
- /src/ringdht/sip_transport_ice.h
- /src/ringdht/sips_transport_ice.cpp
- /src/ringdht/sips_transport_ice.h
- /src/rw_mutex.h
- /src/security/.*
- /src/sip/pattern.cpp
- /src/sip/pattern.h
- /src/sip/pres_sub_client.cpp
- /src/sip/pres_sub_client.h
- /src/sip/pres_sub_server.cpp
- /src/sip/pres_sub_server.h
- /src/sip/sdes_negotiator.cpp
- /src/sip/sdes_negotiator.h
- /src/sip/sdp.cpp
- /src/sip/sdp.h
- /src/sip/sip_utils.cpp
- /src/sip/sip_utils.h
- /src/sip/sipaccount.cpp
- /src/sip/sipaccount.h
- /src/sip/sipaccountbase.cpp
- /src/sip/sipaccountbase.h
- /src/sip/sipcall.cpp
- /src/sip/sipcall.h
- /src/sip/sippresence.cpp
- /src/sip/sippresence.h
- /src/sip/siptransport.cpp
- /src/sip/siptransport.h
- /src/smartools.cpp
- /src/smartools.h
- /src/string_utils.cpp
- /src/string_utils.h
- /src/thread_pool.cpp
- /src/thread_pool.h
- /src/threadloop.cpp
- /src/threadloop.h
- /src/upnp/.*
- /src/utf8_utils.cpp
- /src/utf8_utils.h
- /src/windirent.h
- /src/winsyslog.c
- /src/winsyslog.h
component_depth: 1
languages:
- cpp
- script
